<a href="https://colab.research.google.com/github/Taeho-Kim-0322/Deep_Learning_Start/blob/master/%EB%AF%B8%EB%8B%88_%EC%8B%A4%EC%8A%B51_CNN%EA%B3%BC_%EC%B9%9C%ED%95%B4%EC%A7%80%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1D CNN과 친해져요 :)

In [16]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv1D, MaxPool1D, GlobalMaxPooling1D

1. 길이가 10 토큰인 문장을 임베딩 사이즈=32로 임베딩한 것에 CNN 적용하기

In [3]:
BATCH_SIZE = 1
SEQ_LEN = 10
EMBEDDING_SIZE = 32

embedded_input = np.array(np.random.normal(size=(BATCH_SIZE, SEQ_LEN, EMBEDDING_SIZE)), dtype=np.float32)
print(embedded_input.shape)

(1, 10, 32)


In [4]:
KERNEL_SIZE1 = 3
NUM_FEATURE_MAP = 10

cnn_applied1 = Conv1D(filters = NUM_FEATURE_MAP, 
                     kernel_size = KERNEL_SIZE1, 
                     activation='relu')(embedded_input)

In [5]:
print(cnn_applied1.shape)

(1, 8, 10)


In [6]:
KERNEL_SIZE2 = 4
NUM_FEATURE_MAP = 10

cnn_applied2 = Conv1D(filters = NUM_FEATURE_MAP, 
                     kernel_size = KERNEL_SIZE2, 
                     activation='relu')(embedded_input)

In [7]:
print(cnn_applied2.shape)

(1, 7, 10)


2. CNN feature map에 Max Pooling 적용하기

In [8]:
POOL_SIZE1 = SEQ_LEN - KERNEL_SIZE1 + 1
## <- 이 계산을 알아서 해주는 것이 GlobalMaxPooling1D !!!
print("CNN applied size for kernel {} => {}".format(KERNEL_SIZE1, cnn_applied1.shape))
print("Pooling size for kernel {}     => {}".format(KERNEL_SIZE1, POOL_SIZE1))

max_pool_applied1 = GlobalMaxPooling1D()(cnn_applied1)
print(max_pool_applied1.shape)

CNN applied size for kernel 3 => (1, 8, 10)
Pooling size for kernel 3     => 8
(1, 10)


In [9]:
embedded_input.shape

(1, 10, 32)

In [10]:
cnn_applied1.shape

TensorShape([1, 8, 10])

In [11]:
[a[1]for a in cnn_applied1[0]]

[<tf.Tensor: shape=(), dtype=float32, numpy=1.6879379>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.1281588>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.5757378>,
 <tf.Tensor: shape=(), dtype=float32, numpy=2.2364829>,
 <tf.Tensor: shape=(), dtype=float32, numpy=1.4315151>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.85107756>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>]

In [12]:
max_pool_applied1[0]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.3943576, 2.2364829, 3.108915 , 1.6628414, 2.504888 , 2.6177402,
       2.201215 , 1.3248333, 2.2635443, 2.4062645], dtype=float32)>

In [13]:
POOL_SIZE2 = SEQ_LEN - KERNEL_SIZE2 + 1
## <- 이 계산을 알아서 해주는 것이 GlobalMaxPooling1D !!!
print("CNN applied size for kernel {} => {}".format(KERNEL_SIZE2, cnn_applied2.shape))
print("Pooling size for kernel {}     => {}".format(KERNEL_SIZE2, POOL_SIZE2))

max_pool_applied2 = GlobalMaxPooling1D()(cnn_applied2)
print(max_pool_applied2.shape)

CNN applied size for kernel 4 => (1, 7, 10)
Pooling size for kernel 4     => 7
(1, 10)


3. 만들어진 feature들을 concat

In [17]:
concated_feature = tf.keras.layers.concatenate([max_pool_applied1, max_pool_applied2], axis=-1)
print(concated_feature.shape)

(1, 20)
